/**
 * Audit Actions for Security Event Logging
 *
 * Used by the AuditLogService to track security-relevant events
 * throughout the application for compliance and security monitoring.
 *
 * @see https://github.com/CommonwealthLabsCode/qckstrt/issues/191
 */
export enum AuditAction {
  // Authentication - Login/Logout
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',

  // Authentication - Password Management
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_CHANGE_FAILED = 'PASSWORD_CHANGE_FAILED',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_RESET_FAILED = 'PASSWORD_RESET_FAILED',

  // Authentication - Registration
  REGISTRATION = 'REGISTRATION',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',
  USER_CONFIRMED = 'USER_CONFIRMED',

  // Authentication - Passkey (WebAuthn)
  PASSKEY_REGISTRATION = 'PASSKEY_REGISTRATION',
  PASSKEY_REGISTRATION_FAILED = 'PASSKEY_REGISTRATION_FAILED',
  PASSKEY_AUTHENTICATION = 'PASSKEY_AUTHENTICATION',
  PASSKEY_AUTHENTICATION_FAILED = 'PASSKEY_AUTHENTICATION_FAILED',
  PASSKEY_DELETED = 'PASSKEY_DELETED',

  // Authentication - Magic Link
  MAGIC_LINK_SENT = 'MAGIC_LINK_SENT',
  MAGIC_LINK_VERIFIED = 'MAGIC_LINK_VERIFIED',
  MAGIC_LINK_FAILED = 'MAGIC_LINK_FAILED',

  // Authorization
  AUTHORIZATION_DENIED = 'AUTHORIZATION_DENIED',
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',

  // Security Events
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  SESSION_EXPIRED = 'SESSION_EXPIRED',

  // CRUD Operations
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  // Bulk Operations
  BULK_READ = 'BULK_READ',
  BULK_UPDATE = 'BULK_UPDATE',
  BULK_DELETE = 'BULK_DELETE',

  // Special Operations
  UPLOAD = 'UPLOAD',
  DOWNLOAD = 'DOWNLOAD',
  SEARCH = 'SEARCH',
  EXPORT = 'EXPORT',
}
