FROM nginx:1.23.3-alpine

ADD ./nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./nginx/.certs/localhost.crt /etc/nginx/certs/server.crt
ADD ./nginx/.certs/localhost.key /etc/nginx/certs/server.key

EXPOSE 80 443

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1