import nextPlugin from "eslint-config-next";
import prettierConfigRecommended from "eslint-plugin-prettier/recommended";

const config = [
  ...nextPlugin,
  prettierConfigRecommended, // Last since it disables some previously set rules
  {
    ignores: [
      ".next/*",
      // Generated by @opennextjs/cloudflare, and gitignored — but ESLint has
      // its own ignore list and was still linting it. `pnpm build` runs
      // `prebuild: pnpm lint`, so once a Cloudflare build had produced
      // .open-next/ the NEXT build linted that output and failed on 35
      // prettier violations in machine-generated code. Self-inflicted
      // deadlock: building made the build fail.
      //
      // Invisible in CI, which lints a fresh checkout where .open-next/ does
      // not exist yet — it only ever reproduces on a machine that has run a
      // Cloudflare build.
      ".open-next/*",
      "jest.config.js",
      "cypress.config.ts",
      "public/sw.js",
      "playwright-report/*",
      "test-results/*",
    ],
  },
];

export default config;
