/**
 * Negative control for petition retrieval (#1074, subtask 5), against a real
 * Postgres and vectors from the real embedding model.
 *
 * ── Why this test exists, and what it is worth ───────────────────────────
 *
 * #1074 originally required refusal when a scan matched nothing: "no analysis
 * is produced". That was dropped, because a hard gate is a dead end for every
 * local, county and municipal petition — measures with no Secretary of State
 * filing that will never be in the corpus. What replaced it is disclosure
 * rather than detection: we do not claim to identify fakes, we state clearly
 * when we could not verify.
 *
 * So this assertion is deliberately weaker than the criterion it descends
 * from. It cannot show that an unfiled measure is recognised as unfiled —
 * retrieval cannot tell "a real county measure we do not hold" from "a
 * fabricated sheet", since both are simply absent. It shows only that a
 * well-formed initiative outside the corpus never comes back `verified`, which
 * is the whole guarantee the fallback decision leaves available. The
 * `unverified` label now carries the weight refusal used to, which is why it
 * is worth a test rather than a comment.
 *
 * ── Where the vectors come from ──────────────────────────────────────────
 *
 * `fixtures/petition-retrieval-vectors.json`, generated by the sibling script
 * with the real Xenova model — see its header for why inference cannot run
 * inside Jest. Everything downstream of the vectors is real: the pgvector
 * cosine query, the threshold, and the link write.
 *
 * The positive control is not optional. A test that only asserts "not
 * verified" also passes when the corpus is empty, when the vectors are
 * degenerate, and when the threshold is 1.0 — every broken state this feature
 * can be in. Note it is an *easier* case than reality: at 0.97 it is a
 * near-verbatim reading, where the nine real photographs scored 0.545–0.586.
 * It proves the path is live, not that OCR degradation is survivable.
 */
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { EMBEDDING_DIMENSIONS } from '@opuspopuli/common';
import type { EmbeddingsService } from '@opuspopuli/embeddings-provider';
import type { MetricsService } from '../../../src/common/metrics';
import {
  cleanDatabase,
  disconnectDatabase,
  createUser,
  createDocument,
  getDbService,
} from '../utils';
import {
  RetrievalService,
  MIN_VERIFIED_SIMILARITY,
} from '../../../src/apps/documents/src/domains/services/retrieval.service';
import { PropositionEmbeddingService } from '../../../src/apps/region/src/domains/proposition-embedding.service';
import {
  CORPUS,
  SCAN_OF_A_FILED_MEASURE,
  SCAN_OF_AN_UNFILED_MEASURE,
  embeddingSourceFor,
  fixtureTexts,
} from './fixtures/petition-retrieval-texts';

interface VectorFixture {
  readonly model: string;
  readonly dimensions: number;
  readonly vectors: Record<string, { textHash: string; vector: number[] }>;
}

const FIXTURE = JSON.parse(
  readFileSync(
    join(__dirname, 'fixtures', 'petition-retrieval-vectors.json'),
    'utf8',
  ),
) as VectorFixture;

/** Confidence well above MIN_RETRIEVAL_OCR_CONFIDENCE — the OCR gate is not under test here. */
const GOOD_OCR_CONFIDENCE = 82;

const metricsStub = {
  recordPetitionRetrieval: () => undefined,
} as unknown as MetricsService;

/**
 * Serves the committed vector for an exact text, and throws for anything else.
 *
 * Returning a zero vector or a random one for an unrecognised string would let
 * a future edit to the texts pass silently with meaningless geometry, which is
 * the failure mode this whole suite is about.
 */
const embeddingsStub = {
  getEmbeddingsForQuery: async (text: string): Promise<number[]> => {
    const entry = Object.entries(fixtureTexts()).find(([, t]) => t === text);
    if (!entry) {
      throw new Error(
        'No committed vector for this text. Re-run generate-petition-retrieval-vectors.ts.',
      );
    }
    return FIXTURE.vectors[entry[0]].vector;
  },
} as unknown as EmbeddingsService;

describe('Petition retrieval negative control (real DB)', () => {
  let service: RetrievalService;

  beforeAll(async () => {
    await cleanDatabase();
    const db = await getDbService();
    service = new RetrievalService(db, embeddingsStub, metricsStub);

    for (const measure of CORPUS) {
      const row = await db.proposition.create({
        data: {
          externalId: measure.externalId,
          title: measure.title,
          summary: measure.summary,
          status: 'circulating',
        },
      });
      const { vector } = FIXTURE.vectors[`corpus:${measure.externalId}`];
      const literal = `[${vector.join(',')}]`;
      await db.$executeRaw`
        UPDATE propositions SET embedding = ${literal}::vector WHERE id = ${row.id}
      `;
    }
  });

  afterAll(async () => {
    await disconnectDatabase();
  });

  async function scan(email: string, text: string) {
    const user = await createUser({ email });
    return createDocument({
      userId: user.id,
      type: 'petition',
      extractedText: text,
      ocrConfidence: GOOD_OCR_CONFIDENCE,
      status: 'text_extraction_complete',
    });
  }

  it('asserts against vectors that match the configured model and the current texts', () => {
    // Without this, editing a text or swapping the embedding provider leaves
    // the suite green while measuring geometry that no longer exists.
    expect(FIXTURE.dimensions).toBe(EMBEDDING_DIMENSIONS);
    for (const [key, text] of Object.entries(fixtureTexts())) {
      const entry = FIXTURE.vectors[key];
      expect(entry).toBeDefined();
      expect(entry.vector).toHaveLength(EMBEDDING_DIMENSIONS);
      expect(entry.textHash).toBe(
        createHash('sha256').update(text).digest('hex'),
      );
    }
  });

  it('embeds the same string production embeds', async () => {
    // The vectors were generated from `embeddingSourceFor`, which mirrors
    // `PropositionEmbeddingService.embeddingSource` — the function the region
    // service actually feeds the model. Asserting the mirror against the
    // original is the whole point: if production changes what it embeds, these
    // vectors describe an input the corpus no longer has, and this fails
    // rather than quietly measuring the wrong geometry.
    const measure = { title: CORPUS[0].title, summary: CORPUS[0].summary };
    expect(embeddingSourceFor(measure)).toBe(
      PropositionEmbeddingService.embeddingSource(measure),
    );

    // And the seeded row still holds exactly that string.
    const db = await getDbService();
    const row = await db.proposition.findUnique({
      where: { externalId: CORPUS[0].externalId },
      select: { title: true, summary: true },
    });
    expect(
      PropositionEmbeddingService.embeddingSource({
        title: row!.title,
        summary: row!.summary,
      }),
    ).toBe(embeddingSourceFor(measure));
  });

  it('verifies a scan of a measure that IS in the corpus', async () => {
    const doc = await scan('nc-positive@example.com', SCAN_OF_A_FILED_MEASURE);

    const outcome = await service.findBestMatch(
      doc.id,
      SCAN_OF_A_FILED_MEASURE,
      GOOD_OCR_CONFIDENCE,
    );

    expect(outcome.attempted).toBe(true);
    expect(outcome.match?.externalId).toBe('TEST-NC-0001');
    expect(outcome.match?.similarity).toBeGreaterThanOrEqual(
      MIN_VERIFIED_SIMILARITY,
    );
    expect(outcome.match?.verified).toBe(true);
  });

  it('never verifies a well-formed initiative that was never filed', async () => {
    const doc = await scan(
      'nc-negative@example.com',
      SCAN_OF_AN_UNFILED_MEASURE,
    );

    const outcome = await service.findBestMatch(
      doc.id,
      SCAN_OF_AN_UNFILED_MEASURE,
      GOOD_OCR_CONFIDENCE,
    );

    // Retrieval always returns the nearest of N vectors — "no match" is not
    // something pgvector can say. The guarantee is about the verdict, not
    // about whether anything came back.
    expect(outcome.attempted).toBe(true);
    expect(outcome.match).not.toBeNull();
    expect(outcome.match?.verified).toBe(false);
    expect(outcome.match?.similarity).toBeLessThan(MIN_VERIFIED_SIMILARITY);
  });

  it('writes no link for an unverified match', async () => {
    const doc = await scan('nc-nolink@example.com', SCAN_OF_AN_UNFILED_MEASURE);

    await service.findBestMatch(
      doc.id,
      SCAN_OF_AN_UNFILED_MEASURE,
      GOOD_OCR_CONFIDENCE,
    );

    // The link is what carries a measure's authoritative analysis onto the
    // scan surface (#1074 Phase B). Linking a below-threshold guess would put
    // the wrong filing's analysis beside this scan — the exact failure the
    // threshold exists to prevent.
    const db = await getDbService();
    const links = await db.documentProposition.findMany({
      where: { documentId: doc.id },
    });
    expect(links).toHaveLength(0);
  });
});
