/**
 * The content-transfer bundle (#1305).
 *
 * Shape of the artifact that moves locally-regenerated AI content to another
 * database. A file rather than a live connection, deliberately: this is a
 * rare, high-consequence, one-directional move, and a reviewable artifact
 * beats a connection nobody can inspect before it is applied.
 */

/** Tables this tool is allowed to touch. A CONSTANT, never a parameter. */
export const TRANSFERABLE = [
  'propositions',
  'minutes',
  'representatives',
] as const;

/**
 * Tables that must never appear in a bundle.
 *
 * Listed rather than implied, and asserted by a test. A whole-database dump
 * restored over production would overwrite real accounts with development
 * ones and import personal data — so the tool names what it carries and
 * cannot be pointed elsewhere.
 */
export const FORBIDDEN = [
  'users',
  'user_profiles',
  'user_logins',
  'user_addresses',
  'signal_profiles',
  'sensitive_profiles',
  'documents',
  'audit_logs',
] as const;

/** One claim, as the evidence graph stores it — evidence is NOT carried. */
export interface BundledClaim {
  text: string;
  subjectField: string | null;
  confidence: string | null;
  spanStart: number | null;
  spanEnd: number | null;
  quotedText: string | null;
  citationHint: string | null;
}

/** A proposition's analysis, keyed on its natural key. */
export interface BundledProposition {
  /** Composite natural key — primary keys diverge between databases. */
  regionPluginName: string;
  externalId: string;
  /**
   * SHA-256 of the `full_text` this analysis was generated against.
   *
   * The whole transfer rests on this: if the target's text hashes
   * differently, the analysis does not belong to it and the row is refused.
   */
  sourceTextHash: string;
  analysis: Record<string, unknown>;
  claims: BundledClaim[];
}

/** A minutes summary, keyed on its external id. */
export interface BundledMinutes {
  externalId: string;
  sourceTextHash: string;
  summary: Record<string, unknown>;
  claims: BundledClaim[];
}

/** A representative bio. No source text — bio claims cite structured fields. */
export interface BundledRepresentative {
  externalId: string;
  bio: Record<string, unknown>;
  claims: BundledClaim[];
}

/** What the content was generated by, carried so the target can record it. */
export interface BundleProvenance {
  /** Distinct prompt hashes seen, with the versions that produced them. */
  prompts: { hash: string; version: string | null; count: number }[];
  /** Distinct models seen, with their digests. */
  models: { model: string; digest: string | null; count: number }[];
}

export interface ContentBundle {
  /** Bundle format version, so a stale artifact is refused rather than guessed at. */
  formatVersion: 1;
  exportedAt: string;
  /** Identifies the database this came from, for the audit trail. */
  sourceLabel: string;
  provenance: BundleProvenance;
  /**
   * The verdict distribution at export.
   *
   * The import re-derives evidence rather than carrying it, then asserts the
   * result equals this. Copied verdicts are trusted; re-derived ones are
   * verified — and a difference means something is wrong, so it refuses.
   */
  distribution: Record<string, number>;
  propositions: BundledProposition[];
  minutes: BundledMinutes[];
  representatives: BundledRepresentative[];
}
